/** Shared server-side helpers for booking server functions (admin client loaded lazily). */
import { z } from "zod";

export const BUCKET = "car-media";
export const planEnum = z.enum(["wash", "detail", "signature"]);

export async function admin() {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  return supabaseAdmin;
}

export async function signed(path: string | null | undefined) {
  if (!path) return null;
  const sb = await admin();
  const { data } = await sb.storage.from(BUCKET).createSignedUrl(path, 60 * 60 * 24 * 30);
  return data?.signedUrl ?? null;
}

export const SLOT_ERRORS: Record<string, string> = {
  invalid_slot: "That time isn't one of our slots. Please pick another.",
  past_date: "That slot is already in the past. Please pick a later one.",
  dry_window: "Water needed — pick a morning slot or provide water.",
  blocked: "Rai has blocked that slot (water shortage). Please pick another.",
  // Short on purpose: the UI adds "your photo, plan and details are kept" itself.
  full: "SLOT_FULL: That slot just filled up.",
  not_found: "Booking not found.",
  untimed_hold: "SLOT_FULL: That reservation isn't active — pick a slot again.",
  cancelled: "This booking was cancelled.",
  invalid_status: "That booking can't be changed this way. Please WhatsApp Rai.",
};

/** Public origin of the current request — never trust a client-supplied origin for links we hand out. */
export async function requestOrigin() {
  const { getRequest } = await import("@tanstack/react-start/server");
  const req = getRequest();
  const proto = req?.headers.get("x-forwarded-proto") ?? "https";
  const host = req?.headers.get("x-forwarded-host") ?? req?.headers.get("host");
  if (host) return `${proto}://${host}`;
  return new URL(req?.url ?? "http://localhost:8080").origin;
}

export async function bookSlot(
  id: string,
  date: string,
  time: string,
  mobile: boolean,
  water: boolean,
  days: number,
  status?: "confirmed" | "pending_deposit" | "consultation",
  slots = 1,
) {
  const sb = await admin();
  const { data, error } = await sb.rpc("book_slot", {
    p_booking_id: id,
    p_date: date,
    p_time: time,
    p_mobile: mobile,
    p_water: water,
    p_days: days,
    // Set the status inside the same locked UPDATE, so the slot counts the moment it is reserved.
    ...(status ? { p_status: status } : {}),
    // Hours the service occupies (Full Detail = 2), checked in the same transaction.
    p_slots: Math.max(1, Math.round(slots)),
  });
  if (error) throw new Error("Could not reserve the slot. Please try again.");
  if (data !== "ok") throw new Error(SLOT_ERRORS[data as string] ?? "That slot isn't available.");
}

/** Like bookSlot, but returns the "slot just filled up" message instead of throwing it. */
export async function tryBookSlot(...args: Parameters<typeof bookSlot>): Promise<string | null> {
  try {
    await bookSlot(...args);
    return null;
  } catch (e) {
    const msg = (e as Error).message;
    if (msg.startsWith("SLOT_FULL:")) return msg.replace("SLOT_FULL: ", "");
    throw e;
  }
}

/** How long an unpaid hold keeps its slot (mirrored by getSlots' display filter). */
export const HOLD_MS = 20 * 60_000;

/**
 * Ownership rule for every booking mutation: the manage token is generated by the
 * database when the row is created and handed to whoever CREATED the booking
 * (upload / quick start / waitlist claim). That response is the single
 * ownership-establishing event; every later mutation must present the token.
 * A booking UUID alone is never sufficient — omitting the token is a refusal.
 */
export function assertManageToken(existingToken: unknown, supplied?: string): void {
  const expected = typeof existingToken === "string" ? existingToken : "";
  const got = typeof supplied === "string" ? supplied : "";
  if (!got) throw new Error("This booking can't be modified here — open your booking link again.");
  if (got !== expected)
    throw new Error("This booking link doesn't match — please reopen it from your message.");
}

/**
 * App-side cleanup for expired unpaid holds. Reservation and payment serialize on a
 * single shared advisory lock inside the database (migration 0012); this cleanup is a
 * plain single-statement UPDATE that takes only row locks, so it cannot cycle with
 * the shared-lock-then-row order. It only touches already-expired holds (which
 * book_slot excludes from capacity anyway), and Postgres re-evaluates its WHERE
 * clause when it wins a row that book_slot just re-stamped, so neither path can
 * corrupt the other. Sample (seed) rows are demo content and are left alone.
 * Best-effort, never fatal.
 */
export async function expireStaleHolds(sb: Awaited<ReturnType<typeof admin>>): Promise<void> {
  const cutoff = new Date(Date.now() - HOLD_MS).toISOString();
  // Rows predating hold stamping get a 1-hour grace so a brand-new hold is never
  // mistaken for an unstamped stale one.
  const cutoff60 = new Date(Date.now() - 60 * 60_000).toISOString();
  await sb
    .from("bookings")
    .update({
      status: "lead",
      date: null,
      time: null,
      end_date: null,
      full_day: false,
      held_at: null,
    })
    .eq("status", "pending_deposit")
    .eq("deposit_paid", false)
    .eq("is_seed", false)
    .or(`held_at.lt.${cutoff},and(held_at.is.null,created_at.lt.${cutoff60})`);
}
