/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as OfferIdRouteImport } from './routes/offer.$id'
import { Route as PayBookingIdRouteImport } from './routes/pay.$bookingId'
import { Route as ApiPublicInitiateSarvamCallRouteImport } from './routes/api/public/initiate-sarvam-call'
import { Route as ApiPublicUpdateBookingRouteImport } from './routes/api/public/update-booking'
import { Route as ApiPublicHooksRunScheduleRouteImport } from './routes/api/public/hooks/run-schedule'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfferIdRoute = OfferIdRouteImport.update({
  id: '/offer/$id',
  path: '/offer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBookingIdRoute = PayBookingIdRouteImport.update({
  id: '/pay/$bookingId',
  path: '/pay/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInitiateSarvamCallRoute =
  ApiPublicInitiateSarvamCallRouteImport.update({
    id: '/api/public/initiate-sarvam-call',
    path: '/api/public/initiate-sarvam-call',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUpdateBookingRoute = ApiPublicUpdateBookingRouteImport.update({
  id: '/api/public/update-booking',
  path: '/api/public/update-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunScheduleRoute =
  ApiPublicHooksRunScheduleRouteImport.update({
    id: '/api/public/hooks/run-schedule',
    path: '/api/public/hooks/run-schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/owner': typeof OwnerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/offer/$id': typeof OfferIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/api/public/initiate-sarvam-call': typeof ApiPublicInitiateSarvamCallRoute
  '/api/public/update-booking': typeof ApiPublicUpdateBookingRoute
  '/api/public/hooks/run-schedule': typeof ApiPublicHooksRunScheduleRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/owner': typeof OwnerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/offer/$id': typeof OfferIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/api/public/initiate-sarvam-call': typeof ApiPublicInitiateSarvamCallRoute
  '/api/public/update-booking': typeof ApiPublicUpdateBookingRoute
  '/api/public/hooks/run-schedule': typeof ApiPublicHooksRunScheduleRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/owner': typeof OwnerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/offer/$id': typeof OfferIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/api/public/initiate-sarvam-call': typeof ApiPublicInitiateSarvamCallRoute
  '/api/public/update-booking': typeof ApiPublicUpdateBookingRoute
  '/api/public/hooks/run-schedule': typeof ApiPublicHooksRunScheduleRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/owner'
    | '/.well-known/oauth-protected-resource'
    | '/offer/$id'
    | '/pay/$bookingId'
    | '/api/public/initiate-sarvam-call'
    | '/api/public/update-booking'
    | '/api/public/hooks/run-schedule'
    | '/api/public/hooks/send-reminders'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/owner'
    | '/.well-known/oauth-protected-resource'
    | '/offer/$id'
    | '/pay/$bookingId'
    | '/api/public/initiate-sarvam-call'
    | '/api/public/update-booking'
    | '/api/public/hooks/run-schedule'
    | '/api/public/hooks/send-reminders'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/owner'
    | '/.well-known/oauth-protected-resource'
    | '/offer/$id'
    | '/pay/$bookingId'
    | '/api/public/initiate-sarvam-call'
    | '/api/public/update-booking'
    | '/api/public/hooks/run-schedule'
    | '/api/public/hooks/send-reminders'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  OwnerRoute: typeof OwnerRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  OfferIdRoute: typeof OfferIdRoute
  PayBookingIdRoute: typeof PayBookingIdRoute
  ApiPublicInitiateSarvamCallRoute: typeof ApiPublicInitiateSarvamCallRoute
  ApiPublicUpdateBookingRoute: typeof ApiPublicUpdateBookingRoute
  ApiPublicHooksRunScheduleRoute: typeof ApiPublicHooksRunScheduleRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$id': {
      id: '/offer/$id'
      path: '/offer/$id'
      fullPath: '/offer/$id'
      preLoaderRoute: typeof OfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$bookingId': {
      id: '/pay/$bookingId'
      path: '/pay/$bookingId'
      fullPath: '/pay/$bookingId'
      preLoaderRoute: typeof PayBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/initiate-sarvam-call': {
      id: '/api/public/initiate-sarvam-call'
      path: '/api/public/initiate-sarvam-call'
      fullPath: '/api/public/initiate-sarvam-call'
      preLoaderRoute: typeof ApiPublicInitiateSarvamCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/update-booking': {
      id: '/api/public/update-booking'
      path: '/api/public/update-booking'
      fullPath: '/api/public/update-booking'
      preLoaderRoute: typeof ApiPublicUpdateBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-schedule': {
      id: '/api/public/hooks/run-schedule'
      path: '/api/public/hooks/run-schedule'
      fullPath: '/api/public/hooks/run-schedule'
      preLoaderRoute: typeof ApiPublicHooksRunScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  OwnerRoute: OwnerRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  OfferIdRoute: OfferIdRoute,
  PayBookingIdRoute: PayBookingIdRoute,
  ApiPublicInitiateSarvamCallRoute: ApiPublicInitiateSarvamCallRoute,
  ApiPublicUpdateBookingRoute: ApiPublicUpdateBookingRoute,
  ApiPublicHooksRunScheduleRoute: ApiPublicHooksRunScheduleRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
